// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbLk8Tc85KApjxVHnbm7_YJgPFE2adQfo',
    appId: '1:770949696728:web:561521ecc00e9badd3dbad',
    messagingSenderId: '770949696728',
    projectId: 'appstore-e91dc',
    authDomain: 'appstore-e91dc.firebaseapp.com',
    storageBucket: 'appstore-e91dc.firebasestorage.app',
    measurementId: 'G-FHMTW95LRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL--gBxt2rVi-5nDkfUJtQz2lJuluWyAY',
    appId: '1:770949696728:android:9cff3ffd540bf8cad3dbad',
    messagingSenderId: '770949696728',
    projectId: 'appstore-e91dc',
    storageBucket: 'appstore-e91dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbt-WXogXptba-ybw_m90Hj0fzKBp_QiU',
    appId: '1:770949696728:ios:407600f37eb0580dd3dbad',
    messagingSenderId: '770949696728',
    projectId: 'appstore-e91dc',
    storageBucket: 'appstore-e91dc.firebasestorage.app',
    iosBundleId: 'com.example.appStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbLk8Tc85KApjxVHnbm7_YJgPFE2adQfo',
    appId: '1:770949696728:web:9e4245d430883c29d3dbad',
    messagingSenderId: '770949696728',
    projectId: 'appstore-e91dc',
    authDomain: 'appstore-e91dc.firebaseapp.com',
    storageBucket: 'appstore-e91dc.firebasestorage.app',
    measurementId: 'G-P39DGCL0W0',
  );
}
